apiVersion: v1
kind: Pod 
metadata:
  name: my-pod
spec:
  containers: 
  - name: my-pod
    image: httpd
    ports:
    - containerPort: 
        port: 80
        protocol: TCP
        target port: 80