apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc
  labels:
   team: dev
spec:
 replicas: 5
 selector:
   team: dev
 template:
  metadata:
    team: dev
  spec: 
   containers:
   - name: c00
     image: tomcat
     ports:
     - containerPort: 8080