apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs
spec: 
  replicas: 3
  selector:
    matchLabels:
      team: dev
  template: 
    metadata: 
      labels: 
        team: dev
    spec:
      containers:
      - name: c00
        image: nginx
        ports: 
         containerPort: 80
