apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  tls.crt: /home/cloudshell-user/my-k8s/objects/ingress/ssl-certificate.pem
  tls.key: /home/cloudshell-user/my-k8s/objects/ingress/ssl-key.pem
type: kubernetes.io/tls