apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  tls.crt: -----BEGIN CERTIFICATE-----
MIIEBzCCAu+gAwIBAgIUMx4rz2IBKP1oD/0Ptv6uKxo5kpYwDQYJKoZIhvcNAQEL
BQAwgZIxCzAJBgNVBAYTAmluMRUwEwYDVQQIDAxtYWhhcmFzaGF0cmExDTALBgNV
BAcMBHB1bmUxEjAQBgNVBAoMCWNsb2RibGl0ejESMBAGA1UECwwJaW5zdGl0dWRl
MQ8wDQYDVQQDDAZwcmF0aG0xJDAiBgkqhkiG9w0BCQEWFWphY2toYXJkbHkzQGdt
YWlsLmNvbTAeFw0yNDAyMTAwNjM5NTFaFw0yNTAyMDkwNjM5NTFaMIGSMQswCQYD
VQQGEwJpbjEVMBMGA1UECAwMbWFoYXJhc2hhdHJhMQ0wCwYDVQQHDARwdW5lMRIw
EAYDVQQKDAljbG9kYmxpdHoxEjAQBgNVBAsMCWluc3RpdHVkZTEPMA0GA1UEAwwG
cHJhdGhtMSQwIgYJKoZIhvcNAQkBFhVqYWNraGFyZGx5M0BnbWFpbC5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmpZOw1EhjHlOS82wLZSqJSCpA
2AuuDKFhWQRyYKIgoKDbHTDrqFRk5pYgLBtDpmOXC0AxJviBQJfQfAdwOhzGrwhz
4Wx4gjn2SRjX8VPmZ4UdWLsvX+MQ0OWQEdVCTaGOBfCAqmXoRTtgD+1noRnKCsb8
qWskJe+PMLszD09EPnkH0t+ZasldQ66igXIHMoYvS2MZMvs4mLWPYzU1h5l4mIhF
tzuHKtxoueWSnqn3OpUHxw9nQm7FwcF6e4KHipQcrq7o0fx6n8eYflRERQzIJenS
Pp+AtqxQt9JfDrFwm+LiIzdhswp/m2kt023s1QhCav2CUn2ZmRzyKwaGMQrnAgMB
AAGjUzBRMB0GA1UdDgQWBBSAwvUSe6In8EArPp44ovMCFE91cTAfBgNVHSMEGDAW
gBSAwvUSe6In8EArPp44ovMCFE91cTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
DQEBCwUAA4IBAQCNHPieFkPF2EnFdsbylqPZwiJPXVj6UnoJBDQRrwPmatEuQnia
cMeBF+IToywHd+RQPWKatxrx53nL/qNqFNYq8j4AILbjlo0deMN5w+eVOyMh5pkK
pjaRz8pLNNAp0cqUqRLSQrHCsyQ2S+uMoeInxdPpboT38CN1ZDOQDSgfDW8njvqE
JKxusm7MC2kRR9pNuB6bFvTqyKZ5HsO5YtEdMWRJTBnd/uryQ0+SN0gW1FAyT0FI
43J+5z4D4UIFlP0bfWejB6Cgrdmjiavxj+6QYPwtVwbHVxOBKWhiEOyR7+uh+BPF
pNd0s7EI+p30OffXeV8wSPkED7HWeg6LUfU1
-----END CERTIFICATE-----
  tls.key: -----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmpZOw1EhjHlOS
82wLZSqJSCpA2AuuDKFhWQRyYKIgoKDbHTDrqFRk5pYgLBtDpmOXC0AxJviBQJfQ
fAdwOhzGrwhz4Wx4gjn2SRjX8VPmZ4UdWLsvX+MQ0OWQEdVCTaGOBfCAqmXoRTtg
D+1noRnKCsb8qWskJe+PMLszD09EPnkH0t+ZasldQ66igXIHMoYvS2MZMvs4mLWP
YzU1h5l4mIhFtzuHKtxoueWSnqn3OpUHxw9nQm7FwcF6e4KHipQcrq7o0fx6n8eY
flRERQzIJenSPp+AtqxQt9JfDrFwm+LiIzdhswp/m2kt023s1QhCav2CUn2ZmRzy
KwaGMQrnAgMBAAECggEAOn8yycaqpkh188aI7bMUbF4tntd3uh/q4j4aJoAvSR65
eFDV5FMRVN3wYti4tVWJ7fJgFSDl6JEg+WkgP0/W3BOC9xJxPhgQepiMJPksh1td
ScDk7CtPjI6Xlqv73StdA3qoQrIN1au/vOe6YT8Wy2pfET/zQRwj7HKhs7mzDHQE
ibIaFmwzrz/FIlCTkHRRZmctbOd1GzL843ObMUDjIiJbP/DFnwhDZv7Zd7Dvq+lO
V806fhOZtirJ9cJvSOcW63jsxwQMJize9LxvUZSQr8Z6V+b/JmOEv1IWGHbv5skd
f+4iTGeFvP4BVgHRJEtrhduxDJfHEDwzzg4Jrd6p8QKBgQDMJGmMUtO6Y+e4hJWN
/A0HqK5cwFpy3Pr9MDcMQmtFGnryOxn6VQceI4MbFCxeKYJx9XD+mk77cvKIXWvM
nW3a1zdko1N176JKhCKbQFU4m9S1uDDi+WgusmCVMhj1TXovzaR3gzPdPMNDtLdS
/jndu2EGtmUfOYluRFw65/Ky6QKBgQDQ+sufGKDOMV9icnmvcOnZhdEd8AKV1nUL
3EHL+gUwqzGib0zhw6Dq3lrfvg+TUFzIxxfj35bg/h6kb+exmq0fcUoyVfRbuEfu
/YIUk5b1Ho+nEnuaTjwVXKdpZGkSnbqSsnBp/9abqAucG9VDObEUR40b1q3Gn1Ix
rNGz58YNTwKBgG9Ikjkqlb0P5SvTKuvhsQCx1Ys+WJAxIqmO9RM7ydo72zXdPgYW
//BQD5JdZupV2oRg9h305IVyXgA0XSWH1HDtzYaQ+lhaL7BLY8oaQdrAKC5/oDa7
Gy4Jk1kBnFVszOTuR2/XGBjMnO11wFH/wG+9S+Eq4Okqpl5z6Ys7EjSxAoGBALHd
Mx820+6KwRdGPWFf5fjYVxJ264xiGf69OVcFdhNlMXqB5lqkqTodhBS4bANCu6W7
Jg8xhvX581SbVgSolD6VqsPKuo6x+q9jHqqqrynzF+rn5UGA4sx/rpEZ///zNQ+U
Re9B64NR9IeqfMmZuah7+ZK/FepeQZO79kN7ueorAoGAbgTaww5ittDqJnEObwQl
BYCE6aBMdL+jT1bX7t7V0xUv6lQ1lHQpTwNNAO9ciEf31+c/KJXWeVkD/Ss1m1j4
B0A1yGMjZ7YFYhYfMs+VmdYsJdUgA5s2eJyhLdaKzIievFBBGg29NlF2OSlvBuWd
RhNS5wIw5QzEZTFgdV0Nqyw=
-----END PRIVATE KEY-----
type: kubernetes.io/tls