apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: prathammore0025/back:v1 
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate