---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3tier-back
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: student
          image: prathammore0025/docker:back
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 200Mi
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
...

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
    - port: 80
      targetPort: 8080 
      protocol: TCP
  type: NodePort    
  selector:
    app: my-app
...