apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: front-svc
      port:
        number: 80
  rules:
    - host: "a2985ca7d350b4c01b85e40b9a305415-6d34c8e2ac86a609.elb.eu-west-3.amazonaws.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: front-svc
              port:
                number: 80