apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: front-svc
      port:
        number: 80
  rules:
    - host: " af5ab5a85717f46e287839071c5ca535-38f1a5ae06198f8d.elb.eu-west-3.amazonaws.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: front-svc
              port:
                number: 80